import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/custom/ThemeProvider";
import Footer from "@/components/custom/Footer";
import { Inter } from "next/font/google";
import { NavbarComponent } from "@/components/custom/Navbar";
const inter = Inter({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.className}>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative flex w-full flex-col items-start justify-start overflow-hidden">
            <NavbarComponent />
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
